language: node_js
node_js:
  - '0.12.7'
before_install:  
    - source /etc/lsb-release && echo "deb http://download.rethinkdb.com/apt $DISTRIB_CODENAME main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list
    - wget -qO- http://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -
    - sudo apt-get update -q
    - sudo apt-get -y --force-yes install rethinkdb
after_install:
  - node app.bundle.js
before_script:
  - rethinkdb --daemon
script:
  - while ! echo exit | nc localhost 28015; do sleep 10; done
  - while ! echo exit | nc localhost 29015; do sleep 10; done
  - mocha
notifications:
  slack:
    secure: K0Y3yKDrn+F1Zq7A/KVKPyyApbAeAeW6NORy5Y2HwhrCSSXxEi1N+t+pV2nGcSgjbcLOyvQa8qXWfqe6chawsrHcuObxsRH8w1d00O4CtZRfKv/qDxPQz9LQCHmFD/TwWcTV13X/LDLwpB3xbo1gg1JMNzW4t0wW3bb7OH34RfMvUOXSRJHWB+PGAod3Tr0az7dioEdnU0M7O9QYPw+dKHw5XeZsOeUROOqND37rhdjkzPMaa0Zyg82/NVLgab9quYvL6LuygXdZDtqDsvLqxCXCiiIszXP6bUceBUC09KjrE45rpOoNDmbIFChggkyIapEzwIa8Rybige+LDsFIstrJZX3bqrAR2uRrFtOHD0oltv6kQ+uyUdwYJUl+1/1Og+IZpdpLshuuKSYzF/28DDFWbVISZ276BCkzoap3REWevRnl1kGn3hEgMpN10TciSHr78FT243IVsMm5sUXVQtTHATYWb/DidDoYnC0FDOdDlzUreLN8DdccCLqFv0G+xY9wp2gIBZHEaZoazxRJPUk8FEYlMWzKZiAfkAPS9gMmthRcIMRTqKBpQQAr/wzFBS9TsLBA6hYeJTOoT7NtpQCMMjIBDX46r/lPciXIjiGA98FlCg7ExY0mTI/D0b2ZQAZzh5exC/m/hPqAWjuzEoqsmldO5zpgmxmWVZLmAzg=
